/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.company.app.client.growstuff.models

import com.squareup.moshi.Json

/**
 * Attributes
 * @param name null
 * @param enWikipediaUrl null
 * @param perennial null
 * @param medianLifespan null
 * @param medianDaysToFirstHarvest null
 * @param medianDaysToLastHarvest null
 */
data class GetCropsDataAttributesResponse(
  // null
  val name: String? = null,
  // null
  @Json(name = "en-wikipedia-url")
  val enWikipediaUrl: String? = null,
  // null
  val perennial: Boolean? = null,
  // null
  @Json(name = "median-lifespan")
  val medianLifespan: Int? = null,
  // null
  @Json(name = "median-days-to-first-harvest")
  val medianDaysToFirstHarvest: Int? = null,
  // null
  @Json(name = "median-days-to-last-harvest")
  val medianDaysToLastHarvest: Int? = null,
)
