/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.company.app.client.growstuff.models

/**
 * Associate data
 * @param plantings
 * @param seeds
 * @param harvests
 * @param photos
 * @param parent
 */
data class GetCropsDataRelationshipsResponse(
  val plantings: DataRelationshipsOwner? = null,
  val seeds: DataRelationshipsOwner? = null,
  val harvests: DataRelationshipsOwner? = null,
  val photos: DataRelationshipsOwner? = null,
  val parent: DataRelationshipsOwner? = null,
)
